### ISSUE TITLE
no reset possible

### ISSUE THREAD

**Issue by detmet** [ITC-CRIB/qgis-light#1]
Unfortunately, the plugin is a one-way street: the reset button does not appear. 
I would advise against installing it for the time being.

**Comment by girgink** [comment]
Can you please clarify what you mean with reset button does not appear? The plugin gets activated only if you click the button added to the project toolbar indicated with a plain QGIS logo, or selecting `Toggle QGIS Light` item under the view menu. Once it is activated, you can revert back to the standard interface by clicking colored QGIS tool button located at the end of the main toolbar. Screenshots are available in the readme document.

**Comment by detmet** [comment]
Hello,

you wrote: "Once it is activated, you can revert back to the standard 
interface by clicking colored QGIS tool button located at the end of the 
main toolbar". Exactly this exit button (as shown in 
/qgis-light-enabled.png/ at the right margin) did not appear anywhere in 
the toolbar or in the menus. So I could not restore the previous 
standard interface. (Iam trying now to repair my QGis installation.)
I use Qgis 3.38.3 and Windows 10.

Best wishes
detmet



Am 25.09.2024 um 16:25 schrieb Serkan Girgin:
> Can you please clarify what you mean with reset button does not 
> appear? The plugin gets activated only if you click the button added 
> to the project toolbar indicated with a plain QGIS logo, or selecting 
> Toggle QGIS Light item under the view menu. Once it is activated, you 
> can revert back to the standard interface by clicking colored QGIS 
> tool button located at the end of the main toolbar. Screenshots are 
> available in the readme document.

**Comment by girgink** [comment]
Can you please send a screenshot? Also log messages will help to identify the issue, you can access them by clicking the messages icon at the right bottom corner.

You can uninstall the plugin manually by deleting the `qgis-light` folder under your QGIS profile directory. In my case, it is located under `C:\Users\<Username>\AppData\Roaming\QGIS\QGIS3\profiles\Default\python\plugins\`.

**Comment by liphy** [comment]
The same question, @detmet  I wang o know how to repair QGIS? thanks.

**Comment by girgink** [comment]
I added a note to the installation section of the Readme document for the use of a profile before enabling the plugin. This will enable to switch the default profile if something goes wrong.

**Comment by girgink** [comment]
@detmet, can you please send the version information available in the about dialog (Qt, Python, etc.), including active plugins?

**Comment by detmet** [comment]
I have now tried release v0.1.1. The error I had during the installation of the first release last week (the reset button was missing after the start of the plugin) does not occur with this release. I have not changed anything in my QGIS installation in the meantime. Now I have to say that gqis-light it is a very useful plugin!
